[package]
name = "penrose_wm"
version = "0.1.0"
edition = "2024"

[[bin]]
doc = false
name = "penrose_wm"
path = "src/main.rs"

[dependencies]
penrose = "0.4.0"
penrose_ui = "0.4.0"
simplelog = "0.12.2"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
